# Generated by Django 3.2 on 2024-02-24 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productlist_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlist',
            name='created_at',
        ),
    ]
